CREATE TABLE IF NOT EXISTS Questions(
    QuestionID INTEGER PRIMARY KEY AUTOINCREMENT,
    PollID INT NOT NULL,
    Question VARCHAR (255) ,
    QType VARCHAR (255) ,
    FOREIGN KEY (PollID) REFERENCES Polls(PollID)
)
